### ISSUE TITLE
T440s backlight on L440?

### ISSUE THREAD

**Issue by ludufre** [Snikii/Lenovo-Thinkpad-L440#4]
Can you tell if the backlit T440s keyboard would work on the L440? The two are very similar ...

**Comment by Sniki** [comment]
> Can you tell if the backlit T440s keyboard would work on the L440? The two are very similar ...

hi @ludufre sorry i didn't see this issue.

No, it didn't, i did order it and installed but it never did work for me.

Either it misses the hardware function or ACPI but it didn't work for me.
